OOP school library: set up associations
olawale-o/school_library pull request #3
Opened 2021-10-04 12:08 UTC by olawale-o

## In this PR, I did the following:

- Create a class **Classroom** with the following:
  - @label instance variable, should be initialized in the constructor.
  - Setter and getter for @label (remember about attr_accessor).
  - Create the has-many/belongs-to relationship between **Classroom** and **Student**. The following should be implemented:
  - Create the has-many side (a classroom has many students).
  - Create the belongs-to side (a student belongs to a classroom).
  - Make sure that when adding a student to a classroom it also sets the classroom for the student.
  - Make sure that when setting the classroom for a student it also adds it to the classrooms' students.
- Create a class **Book** with the following:
  - **@title** and **@author** instance variables, should be initialized in the constructor.
  - Setters and getters for instance variables (remember about attr_accessor).
- Create a class Rental with the following:
  - @date instance variable, should be initialized in the constructor.
  - Setter and getter for @date (remember about attr_accessor).
  - Create the many-to-many (also has-many-through) relationship between **Person** and **Book** using the intermediate class - -- Rental. The following should be implemented:
  - Create the has-many side of **Book** and **Rental** (a book has many rentals).
  - Create the belongs-to side of **Rental** and **Book** (a rental belongs to a book).
  - Create the has-many side of **Person** and **Rental** (a person has many rentals).
  - Create the belongs-to side of **Rental** and **Person** (a rental belongs to a person).
- Modify the constructor of Rental so **Book** and **Person** are set in it.

2021-10-04 13:54 UTC, ElijahTobs requested changes
# Status: Changes Required ⚠️ 🚦
## Hi @olawale-o  👋

You've done really well so far! 👍 

## Major Highlights 💯 

Your README is professional ✔️ 
You've followed the Github flow rules. ✔️ 
Good commit messages ✔️ 
Good PR title and very comprehensive PR summary✔️ 

_However, there are some changes that you are required to make before this project can be approved._

## Required Changes ♻️

___See the inline comments below___

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

#### "Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
## Happy Coding :computer: 

_Reviewed by_  **Elijah O. Ayandokun**

2021-10-04 13:54 UTC, ElijahTobs commented on book.rb
> +end
- [ ] You're expected to create a `many-to-many` (also `has-many-through`) relationship between person and book using the intermediate class `Rental`. To achieve that, you should have `getters` and `setters` for `@rentals`. You should also have a method for adding rentals. [This](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) should be of help.

2021-10-04 13:54 UTC, ElijahTobs commented on rental.rb
> +  attr_reader :person, :book
- [ ] `getters` and `setters` should be present for both @book and @person instance variables

2021-10-04 13:54 UTC, ElijahTobs commented on person.rb
> +  attr_reader :id, :rentals
- [ ] `getters` and `setters` should be present for @rentals

2021-10-04 13:54 UTC, ElijahTobs commented on person.rb
>    def of_age?
- [ ] Still on the relationships: Since a person can have many rentals, you're expected to have a method for adding rentals in the `Person` class.

2021-10-04 14:52 UTC, olawale-o commented on book.rb
> +end
Thank you for pointing out these corrections
I would like to take your attention back to the section of the [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) that was provided by microverse on the many-many relationship  where **Visit** class was used as the has-many-through (intermediate) class between **animal** class and **vet** class
The **vet** class has an instance variable of **@visits** and an **attr_reader: visits** and neither **setters nor getters** were defined for **visits** as you suggested I define for **rentals** in **book class**
In my case, the **book** class represents the **vet** class where I have **@rentals** as my instance variable and **attr_reader: rentals**

![shot1](https://user-images.githubusercontent.com/55432600/135873607-abd75a11-3fc5-4ad9-b4e1-96743d3f9f08.png)

2021-10-04 14:55 UTC, olawale-o commented on rental.rb
> +  attr_reader :person, :book
Thank you for your time for pointing this out
I would like to refer you to this section of this [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) provided by microverse
The **Visit** class is the has-many-through (intermediate) class between **animal class and vet class**
neither setters nor getters were defined for **animal and vet**,  instances of them were passed as parameters on instantiation of the **visit** class
In my case, the **Rental** represents the **Visit** class **person and book** are arguments
![shot2](https://user-images.githubusercontent.com/55432600/135874124-c351dae7-7f9e-4569-a3a9-3ef08610e73d.png)

2021-10-04 15:00 UTC, olawale-o commented on person.rb
> +  attr_reader :id, :rentals
Thank you for pointing out these corrections
I would like to take your attention back to the section of the [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) that was provided by microverse on the many-many relationship  where **Visit** class was used as the has-many-through (intermediate) class between **animal** class and **vet** class
The **animal** class has an instance variable of **@visits** and an **attr_reader: visits** and neither **setters nor getters** were defined for **visits** as you suggested I define for **rentals** in **person class**
In my case, the **person** class represents the **animal** class where I have **@rentals** as my instance variable and **attr_reader: rentals**
![shot4](https://user-images.githubusercontent.com/55432600/135874957-ce9f11ce-ae2c-4620-801f-e3757869a581.png)

2021-10-04 15:04 UTC, olawale-o commented on person.rb
>    def of_age?
Thank you for your effort on the suggestions
I would like to refer you to the [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) that was provided my microverse
on the many-many relationship between **animal and vet** classes in which **visit** class was used as the intermediate class the **animal** class which represent person class in my case, it does not have a method defined to add **visits** as you suggested adding a method on **person** class to add **rentals**
![shot4](https://user-images.githubusercontent.com/55432600/135875559-a197f996-ad21-424c-a0db-a382ef5c2e02.png)

2021-10-05 03:44 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-10-05 03:52 UTC, olawale-o commented
Hi @arslanbisharat
Thank you for your time and effort on the review

2021-10-05 03:54 UTC, merged

2021-10-05 22:20 UTC, SpaYco reviewed
Hello 👋,

_This is an additional review as a result of the second opinion request._

It looks like you handled this well, and got your project approved, nothing else to say other than good luck with the rest of your projects!

@ElijahTobs please take notes.

Keep rocking 🚀!